/*-
 * +======================================================================+
 * Sfera
 * ---
 * Copyright (C) 2015 - 2016 Sfera Labs S.r.l.
 * ---
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * -======================================================================-
 */

/**
 * 
 */
package cc.sferalabs.sfera.scripts;

import cc.sferalabs.sfera.events.Event;

/**
 * Class for events generated by script nodes.
 * 
 * @author Giampiero Baggiani
 *
 * @version 1.0.0
 *
 */
public class ScriptEvent implements Event {

	private final Object source;
	private final String id;
	private final String subId;
	private final long timestamp;
	private final Object value;

	/**
	 * Constructor.
	 * 
	 * @param source
	 *            the source node
	 * @param sourceId
	 *            the source node ID
	 * @param id
	 *            the event ID
	 * @param value
	 *            the event value
	 */
	ScriptEvent(Object source, String sourceId, String id, Object value) {
		this.timestamp = System.currentTimeMillis();
		this.source = source;
		this.id = sourceId + "." + id;
		this.subId = id;
		this.value = value;
	}

	@Override
	public String getId() {
		return id;
	}

	@Override
	public String getSubId() {
		return subId;
	}

	@Override
	public Object getSource() {
		return source;
	}

	@Override
	public long getTimestamp() {
		return timestamp;
	}

	@Override
	public Object getValue() {
		return value;
	}

	@Override
	public Object getSimpleValue() {
		return getValue();
	}

}
